FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

RUN pip install uv

WORKDIR /backend

COPY backend/pyproject.toml backend/uv.lock ./

RUN uv sync --all-groups  

COPY backend/ ./

CMD ["sleep", "infinity"]
