name: Main flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review]

jobs:
  extension-test:
    uses: ./.github/workflows/extension.yml
    if: ${{ !github.event.pull_request.draft }}